### ISSUE TITLE
Does not seem to support events

### ISSUE THREAD

**Issue by haroldo-ok** [CurtisHughes/pixel-editor#17]
From the documentation, it does not look like the classes have any way of capturing events; how would I do to get an event every time the user changes a pixel?

**Comment by CurtisHughes** [comment]
Hey @haroldo-ok, the canvas events get pushed to the currently active "tool".  You can see an example with the [Pencil](https://github.com/CurtisHughes/pixel-editor/blob/master/src/tools/Pencil.ts). You can use the existing tools or create a completely new tool that follows the [Tool interface](https://github.com/CurtisHughes/pixel-editor/blob/0690eacc9508c7dc46ef9806bba88d5ba4f679d2/src/types.ts#L19).

Hope that helps 😄

**Comment by haroldo-ok** [comment]
Okay, many thanks.
