### ISSUE TITLE
README improvement

### ISSUE THREAD

**Issue by pietrovismara** [CurtisHughes/pixel-editor#9]
Hey I wanted to say thanks for writing this package, it looks well written and a good fit for my project.

Just a tip if I may: I would add some screenshot in the README file to showcase a bit what it can do. It's a big barrier to have to install the package, setup an example only to maybe find out it's not the right choice.

**Comment by CurtisHughes** [comment]
Glad you like the package! I'll work on adding some screenshots/gifs of the core functionality. Thanks for the suggestion 😄
